indec-it/react-native-survey-commons

README.md, package.json, yarn.lock
feat(package): install new dependencies
=> fix(packages): install and update dependencies

actions/package.json, package.json, reducers/package.json, sagas/package.json, src/actions/index.js, src/actions/network.js, src/actions/sync.js, src/components/Sync/NetworkStatus.js, src/components/Sync/SyncStatus.js, src/components/Sync/index.js, src/components/Sync/styles.js, src/constants/index.js, src/index.js, src/reducers/index.js, src/reducers/network.js, src/reducers/sync.js, src/sagas/index.js, src/sagas/network.js, src/sagas/sync.js, src/services/index.js, src/services/ping.js, src/services/surveys.js, src/services/sync.js, yarn.lock
=> feat(sync): add sync

src/actions/sync.js, src/components/Sync/index.js, src/reducers/sync.js, src/sagas/sync.js
fix(sync): fix when complete sync
=> perf(sync): avoid load surveys on sync completed

src/services/surveys.js
fix(surveys): fix when save survey change id to _id
=> fix(surveys): fix when save survey change id to _id

package.json, src/actions/index.js, src/actions/surveys.js, src/components/AreasList/index.js, src/components/AreasList/styles.js, src/components/Sync/index.js, src/components/Sync/styles.js, src/index.js, src/reducers/index.js, src/reducers/surveys.js, src/sagas/index.js, src/sagas/surveys.js, src/sagas/sync.js, src/services/surveys.js
=>  feat(areas): add AreasList component

src/components/Sync/index.js, src/services/surveys.js
fix(surveys): get more values when fetch areas
=> fix(surveys): get more values when fetch areas

src/components/AreasList/index.js
=> style(areasList): change style for container and title

src/components/AreasList/index.js
fix(areasList): add params to onSelect prop
=> fix(areasList): fix onSelect area parameter

src/components/NavigationButtons/index.js, src/components/NavigationButtons/styles.js
feat(navigator): add navigator buttons
=> feat(navigationButtons): add NavigatorButtons component

src/actions/survey.js, src/components/AddressesList/index.js, src/components/DwellingResponse/index.js, src/components/Form/index.js, src/components/HouseholdsList/index.js, src/components/NavigationButtons/index.js, src/services/survey.js, src/util/historyPropTypes.js, src/util/index.js, src/util/matchParamsIdPropTypes.js
refactor(components): add callbacks for change route
=> refactor(components): add callbacks for change route

model/package.json, src/components/DwellingResponse/index.js, src/model/address.js, src/model/dwelling.js, src/model/index.js, src/model/survey.js
feat(model): add model of survey for remove unnecessary hardcode assigns
=> feat(model): add model of survey for remove unnecessary hardcode assigns

src/components/DwellingResponse/index.js, src/util/matchParamsIdPropTypes.js
fix(dwellingResponse): fix when get params
=> fix(dwellingResponse): rename dwelling param name on route

src/services/survey.js
fix(survey): add class Survey when find dwelling
=> fix(survey): wrap findDwelling result on Survey class

src/components/MembersList/index.js
fix(membersList): send member when select element in table
=> fix(membersList): send member on select from list

src/components/Section/index.js, src/components/Section/styles.js
fix(section): fix when scroll form
=> feat(section): move nav buttons inside ScrollView

src/components/DwellingResponse/index.js, src/components/HouseholdsList/index.js, src/components/MembersList/index.js, src/components/Section/index.js, src/reducers/survey.js, src/util/matchParamsIdPropTypes.js
refactor(components): remove in onSubmit params
=> refactor(components): remove onSubmit arguments

src/reducers/survey.js
fix(reducers): remove saving in some actions
=> fix(reducers): remove saving in some actions

src/components/AddressesList/index.js, src/services/survey.js
fix(addresses): fix when fetch addresses pending
=> fix(addresses): fix fetch inProgress addresses

src/components/DwellingResponse/index.js, src/components/DwellingResponse/styles.js
fix(dwellingResponse): fix navigationButton styles
=> fix(dwellingResponse): fix NavigationButton styles

src/components/DwellingResponse/index.js, src/services/survey.js
fix(dwellingResponse): fix when update dwelling
=> fix(dwellingResponse): fix survey and dwelling class type

src/components/DwellingResponse/index.js, src/services/survey.js
fix(dwellingResponse): fix when create first household
=> fix(dwellingResponse): create first household only once

src/components/HouseholdsList/index.js, src/model/dwelling.js, src/model/household.js, src/services/survey.js
feat(households): disable households if dwelling no response
Depende de: https://github.com/indec-it/react-native-survey-commons/pull/50
=>  feat(households): disable households if dwelling no response

src/actions/survey.js, src/components/DwellingResponse/index.js, src/components/HouseholdsList/index.js, src/sagas/index.js, src/sagas/survey.js, src/services/survey.js
fix(survey): fix when add new household in householdsList
Depende de: https://github.com/indec-it/react-native-survey-commons/pull/51
=> fix(householdsList): fix create household in householdsList

src/services/survey.js
fix(survey): fix when add household to dwelling
=> fix(survey): fix addHouseholdToDwelling

src/components/DwellingResponse/index.js, src/components/DwellingResponse/styles.js, src/components/HouseholdsList/index.js, src/components/HouseholdsList/styles.js, src/components/NavigationButtons/index.js, src/components/NavigationButtons/styles.js, src/components/Section/index.js
style(navigation): change of styles in navigation buttons and views
=> style(navigation): style NavigationButtons and views

src/components/DwellingEditor/index.js, src/components/HouseholdEditor/index.js, src/components/HouseholdResponse/index.js, src/components/MemberEditor/index.js, src/components/NavigationButtons/index.js, src/components/NavigationButtons/styles.js, src/components/Section/index.js, src/model/dwelling.js, src/model/member.js, src/sagas/survey.js, src/services/survey.js
fix(member): fix when update member
=> fix(member): fix handleChangeAnswer and save member

src/actions/survey.js
fix(sagas): fix when receive member
=> feat(actions): remove saved member action

src/util/section.js
fix(section): fix when chapter is root and clean question
=> fix(section): fix cleanQuestions for answers in root chapters

src/components/AddressCard/index.js, src/components/AddressCard/styles.js, src/components/AreasList/index.js, src/components/AreasList/styles.js, src/components/DwellingEditor/index.js, src/components/HouseholdsList/index.js, src/components/HouseholdsList/styles.js, src/components/MembersList/index.js, src/components/MembersList/styles.js
style(membelist): applied styles
=> style(memberList): style MemberList component

src/components/MemberManager/index.js
fix(manager): fix when import util
=> fix(memberManager): fix import utils individually

src/reducers/survey.js
fix(reducers): fix when fetch members
=> fix(reducers): fix receive members flag

src/components/MembersList/index.js
feat(membersList): add button for go to detection
=> feat(membersList): add button for go to detection

src/components/HouseholdsList/index.js
feat(householdsList): add button for change dwelling answer
=> feat(householdsList): add button for change dwelling answer

src/components/Form/index.js
fix(form): fix when questionStyle is undefined
=> fix(form): fix when questionStyle is undefined

src/components/MemberCharacteristics/index.js
refactor(memberCharacteristics): change leftIconOnPress to onPress
=> fix(memberCharacteristics): fix onPress left icon handler

src/components/Form/index.js, src/util/canAnswerQuestion.js, src/util/cleanChildrenQuestions.js, src/util/index.js
feat(form): disable questions if no belong flow
=> feat(form): change hide to disable questions outside flow

src/components/MemberManager/index.js
refactor(memberManager): close selected member when add new member
=> feat(memberManager): close selected member when add new member

src/components/MembersList/index.js, src/components/MembersList/styles.js, yarn.lock
=> style(memberList): top buttons styles

src/components/HouseholdsList/index.js
fix(householdsList): fix when press button
=> fix(householdsList): fix onPress view dwelling button

src/components/MemberEditor/index.js, src/model/dwelling.js, src/model/household.js, src/reducers/survey.js, src/services/survey.js
fix(membersList): fix when check if member is home boss
=> fix(membersList): fix hide trash for home boss member

src/components/MembersList/index.js
feat(membersList): add bool when show characteristics button
=> feat(membersList): add showCharacteristicsButton flag on props

package.json, src/components/HouseholdsList/index.js, src/components/MembersList/index.js, src/services/survey.js, yarn.lock
fix(membersList): fix when show button characteristics
=> fix(membersList): fix show button characteristics

src/services/survey.js
fix(households): fix when add new household
=> fix(survey): fix update dwelling and create default household

src/components/MembersList/index.js
fix(membersList): fix when show button remove member
=> fix(membersList): fix when show button remove member

src/components/MembersList/index.js, src/util/canAnswerQuestion.js
feat(canAnswerQuestion): add multiple parents
=> feat(utils): add AND conditional for canAnswerQuestion

src/components/DwellingEditor/index.js, src/reducers/survey.js
fix(dwelling): send survey when press back button
=> fix(dwellingEditor): send survey param for onPrevious handler

src/components/DwellingsList/index.js, src/components/HouseholdEditor/index.js, src/components/HouseholdResponse/index.js, src/components/MemberEditor/index.js
style(components): loading incorporated in views
=> feat(components): add LoadingIndicator on components mount time

src/components/HouseholdsList/index.js
fix(householdsList): send dwelling when press back button
=> fix(householdsList): send dwelling param for onPrevious handler

src/components/MembersList/index.js, src/components/NavigationButtons/index.js
refactor(navigationButtons): refactor when show buttons
=> feat(navigationButtons): add customizable icons

src/services/survey.js
fix(household): fix when find index of household no disabled
=> fix(household): fix saveHousehold findIndex skipping disabled households

src/components/Form/index.js, src/util/chapterPropTypes.js, src/util/rowsPropTypes.js
refactor(form): add rowPropTypes
=> refactor(form): add rowPropTypes

src/components/AreasList/index.js, src/components/AreasList/styles.js, src/components/HouseholdsList/index.js, src/components/HouseholdsList/styles.js, src/components/MembersList/index.js, src/components/MembersList/styles.js
refactor(components): remove tableContainer style
=> refactor(components): remove tableContainer style

services/package.json
feat(services): add services to new external folder and change sync
=> feat(services): export services from package root

src/util/isQuestionAnswered.js
fix(questionAnswered): fix when validate if answer is array
=> fix(util): fix isAnswered when answer is array

src/components/MemberEditor/index.js
feat(memberEditor): add button for interrupt survey
=> feat(memberEditor): add button for interrupt survey

src/components/HouseholdCloseVisit/index.js, src/services/survey.js
fix(interruption): fix when interruption visit
=> fix(householdCloseVisit): fix handleChange and save

src/components/MemberEditor/index.js, src/util/cleanChildrenQuestions.js
fix(cleanAnswers): remove radio table answers and change button text
=> fix(util): fix cleanChildrenQuestions for radioTable

src/services/survey.js
fix(household): fix when get household
=> fix(survey): fix get household not disabled

src/components/MemberManager/index.js
fix(memberManager): fix validate members when save
=> fix(memberManager): fix validate members on save

src/model/dwelling.js, src/services/survey.js
feat(dwelling): add dwelling visits
=> feat(dwelling): add dwelling visit on not response

src/services/survey.js
fix(survey): set survey resolved when dwelling no response
=> fix(survey): set survey resolved when dwelling no response

src/components/HouseholdsList/index.js
fix(householdsList): fix columns id
=> fix(householdsList): fix columns id

src/components/MemberManager/index.js
fix(memberManager): fix when create new member and assign order
=> fix(memberManager): fix create member ignoring disabled order

src/components/MemberEditor/index.js
fix(memberEditor): hide interrupt button when press
=> fix(memberEditor): hide interrupt button without handler

src/components/MemberEditor/index.js, src/components/MemberEditor/styles.js
style(memberEditor): margin added to the button interrupt survey
=> style(memberEditor): add margin to interrupt button

src/components/AddressCard/index.js, src/components/AddressesList/index.js, src/model/address.js, src/services/survey.js
feat(address): add side and block side
=> feat(components): add block and side in address data

src/sagas/survey.js, src/services/survey.js
fix(member): fix when find member
=> fix(survey): fix find member not disabled

src/reducers/survey.js
fix(reducers): fix when fetch member
=> fix(reducers): fix receive member reducer

src/util/isQuestionAnswered.js
fix(isQuestionAnswered): fix when check radio table answer
=> fix(util): fix isQuestionAnswered for RadioTable answers

src/components/HouseholdsList/index.js, src/components/MembersList/index.js
refactor(membersList): add new prop for change situation label button
=> refactor(membersList): add prop for detection button label

src/components/HouseholdResponse/index.js, src/services/survey.js
generate new household visit when previous response household is different to new response
=> fix(householdResponse): fix when generate new visit

src/components/HouseholdsList/index.js, src/util/getHouseholdHeadName.js, src/util/index.js, yarn.lock
fix(householdsList): find household head in households list
=> fix(householdsList): fix household head name column on list

src/services/survey.js
fix(dwelling): if dwelling response is affirmative change survey state
=> fix(survey): fix dwelling has response set survey in progress

src/actions/sync.js, src/components/Sync/NetworkStatus.js, src/components/Sync/SyncStatus.js, src/components/Sync/index.js, src/components/Sync/styles.js, src/constants/index.js, src/reducers/sync.js, src/sagas/sync.js
style(sync): mobile fisrt sync
=> feat(sync): add expired token message and better UX

src/components/MembersList/index.js
refactor(membersList): replace number to label
=> feat(membersList): add getRelationLabel prop

src/services/survey.js
refactor(address): send all address when fetch
=> feat(address): send all address data for listing

src/components/MemberManager/index.js, yarn.lock
feat(memberManager): add prop to step message
=> feat(memberManager): add confirmRemoveText prop to remove member

src/components/MemberEditor/index.js
feat(handlePreSave): add handlePreSave on submit
=> feat(memberEditor): add onPreSave prop on submit

src/util/isQuestionAnswered.js, yarn.lock
fix(isQuestionAnswered): validate decimal input
=> fix(util): add isQuestionAnswered for decimal input

src/util/isQuestionAnswered.js
fix(isQuestionAnswered): fix when validate decimal input
=> fix(util): fix isQuestionAnswered for decimal input

src/components/MembersList/index.js
refactor(membersList): add prop to change button labels
=> feat(membersList): add prop to change button labels

src/components/Form/index.js, src/util/callFunc.js, src/util/index.js, src/util/isQuestionAnswered.js, src/util/rowsPropTypes.js
fix(isQuestionAnswered): fix when no has answer and no has parents
=> feat(form): add required prop for validate questions

src/util/isQuestionAnswered.js
refactor(isQuestionAnswered): add calc to questions ignore
=> refactor(isQuestionAnswered): add calc to questions ignore

src/components/MemberManager/index.js
change MemberManager method to async for await onPreSave
=> feat(memberManager): add support for async onPreSave prop

src/components/DwellingEditor/index.js, src/components/HouseholdEditor/index.js, src/components/HouseholdResponse/index.js, src/components/HouseholdsList/index.js, src/components/MemberEditor/index.js, src/components/MemberManager/index.js, src/components/MembersList/index.js, src/components/Section/index.js, src/components/Validations/index.js, src/components/Validations/styles.js, src/util/validationResultsPropTypes.js
feat(validations): add Validations component
=> feat(validations): add Validations component

package.json, src/components/Form/index.js, src/components/Form/styles.js, src/util/renderQuestionErrors.js, src/util/validateQuestion.js, yarn.lock
refactor(form): replace TextError Component for Alert
=> refactor(form): replace TextError Component for Alert

src/sagas/index.js, src/sagas/survey.js, yarn.lock
this is for remove all surveys in client project.
=> feat(sagas): add sagas for remove all surveys

src/components/AddressCard/index.js
refactor(addressCard): add description field to card
=> refactor(addressCard): add description to AddressCard component

src/components/MembersList/index.js
refactor(membersList): change order buttons
=> refactor(membersList): reorder buttons on MembersList component

src/components/DwellingVisits/index.js, src/components/HouseholdsList/index.js, src/components/SurveyDetails/index.js, src/constants/index.js
refactor(surveyDetails): add surveyDetails tabs
=> refactor(surveyDetails): add tabs on SurveyDetails component

src/components/MemberManager/index.js
refactor(memberManager): send old members to validate function
=> refactor(memberManager): send old members to validate function

src/components/HouseholdsList/index.js, src/components/SurveyDetails/index.js
refactor(householdsList): add function for add new household
=> refactor(householdsList): add function for add new household

src/components/SurveyDetails/index.js, src/constants/index.js
refactor(surveyDetails): change tab orders
=> refactor(surveyDetails): change tab orders

src/components/HouseholdCloseVisit/index.js, src/components/HouseholdEditor/index.js
fix(household): fix when state is checked
=> fix(household): fix when state is checked

src/model/dwelling.js
refactor(model): remove create first household default
=> refactor(model): remove create first household default

src/components/MemberEditor/index.js
fix(memberEditor): fix when press interrupt button
=> fix(memberEditor): fix onInterrupt handler on MemberEditor component

src/components/DwellingCloseVisit/index.js, src/components/DwellingEditor/index.js, src/components/HouseholdCloseVisit/index.js, src/components/HouseholdEditor/index.js, src/components/HouseholdResponse/index.js, src/components/HouseholdsList/index.js, src/components/MemberEditor/index.js, src/components/MemberManager/index.js, src/services/survey.js, src/util/dwellingVisitPropTypes.js, src/util/householdVisitPropTypes.js, yarn.lock
- rename nextProps to props
- validate props against currentState
- add id to some fields
=> fix(app): rename nextProps and validate props and currentState

src/components/HouseholdResponse/index.js
fix(householdResponse): fix when validate if chapter is complete
=> fix(householdResponse): fix validate chapter completion

src/components/HouseholdEditor/index.js, src/components/MemberEditor/index.js, src/reducers/survey.js
fix(editors): add interrupt household and member
=> fix(components): add interrupt household and member actions

src/services/survey.js
fix(dwelling): save dwelling as an instance
=> fix(survey): save dwelling and return instance

src/services/survey.js
if exists last visit omit "end" and return the other properties
=> fix(survey): fix fetch a new current household visit data

src/reducers/survey.js, src/services/survey.js
set survey's reducers as an empty object
=> fix(reducers): fix survey initial state

src/sagas/survey.js, src/services/survey.js
fix(sagas): send household when save member
=> fix(sagas): update household when member is saved

src/reducers/survey.js
fix(reducers): clean household when fetch dwelling and clean member when fetch household
=> fix(reducers): clean household when fetch dwelling and clean member when fetch household

src/util/isQuestionAnswered.js
fix(isQuestionAnswered): add integerInput if question is answered
=> fix(util): add check isQuestionAnswered to integerInput

src/components/SurveyDetails/index.js, yarn.lock
refactor(surveyDetails): add dwellingVisitsColumns propTypes
=> feat(surveyDetails): add dwellingVisitsColumns prop

src/components/MemberManager/index.js
refactor(memberManager): add dynamic label
=> feat(memberManager): add title prop on component

src/components/MembersList/index.js
refactor(membersList): add dynamic label
=> feat(membersList): add title prop on component

src/components/DwellingCloseVisit/index.js, src/components/HouseholdResponse/index.js
refactor(visits): add user when create or close visit
=> feat(visits): set session user on create or close visit

src/util/alertIncompleteSection.js, src/util/alertIncompleteSectionOnBack.js
refactor(incompleteSection): change message when chapter is incomplete
=> feat(incompleteSection): change message when chapter is not valid

src/util/alertIncompleteSectionOnBack.js
refactor(alertIncompleteSectionOnBack): change message
=> feat(util): change alertIncompleteSectionOnBack message

src/components/MembersList/index.js
style(membersList): add styles in button
=> style(membersList): add margin to to buttons

src/components/AddressCard/index.js, src/components/SurveyDetails/index.js
fix(surveyDetails): change defaultProps
=> fix(surveyDetails): change defaultProps for address and dwelling

src/components/AreasList/index.js, src/components/HouseholdsList/index.js, src/components/MembersList/index.js
fix(columns): add arrayOf in columns
=> fix(components): add arrayOf in columns propType

src/util/dwellingVisitPropTypes.js, src/util/householdVisitPropTypes.js
fix(util): change propTypes date
=> fix(util): fix propType for Date props

src/util/householdVisitPropTypes.js
fix(householdVisitPropTypes): fix instanceOf text
=> fix(householdVisitPropTypes): fix instanceOf text

src/sagas/survey.js
fix(closeHouseholdVisit): update household when close visit
=> fix(survey): update household on app state after close visit

src/components/AddressCard/index.js
refactor(addressCard): change labels
=> feat(addressCard): upgrade AddressCard to use lot field

.huskyrc.json, commitlint.config.js, package-lock.json, package.json, src/components/DwellingEditor/index.js, src/components/HouseholdEditor/index.js
upgrade babel-eslint@10.0.1, husky@1.3.1, @commitlint/cli@7.2.1
=> fix(packages): upgrade eslint to v5.11.1

src/components/DwellingEditor/index.js, src/components/HouseholdEditor/index.js, src/components/HouseholdResponse/index.js, src/components/MemberEditor/index.js, src/components/NavigationButtons/index.js, src/components/Section/index.js
add button for interrupt survey and spread props on NavigationButtons component for validate if has back button, previous button or interrupt button
=> feat(navigationButtons): add button for interrupt survey

.npmignore, package-lock.json, package.json, src/components/SurveyDetails/index.js
fix(surveyDetails): fix when import columnPropTypes of rn-rable
=> fix(surveyDetails): fix when import columnPropTypes of rn-rable
